# Generated by Django 5.1.7 on 2025-03-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientpage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='clientpage',
            name='title',
        ),
        migrations.AddField(
            model_name='clientpage',
            name='client_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='company_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='is_consultant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='project_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='project_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='clientpage',
            name='project_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
